### ISSUE TITLE
Nifi Atlas Bridge Development Opportunity #1

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/nifi-atlas#2]
<p>We are looking for help building an Apache NiFi-Atlas bridge. We want it to process NiFi provenance data and log this in Apache Atlas as lineage metadata to support our planned use of HortonWorks Data Governance framework.</p>
<p>More specifically, we want to be able to record in Atlas the "logical" lineage of a file from input all the way to being saved to HDFS or a database even though it was manipulated several times. Also, we would like to be able to process the provenance data as the processes proceed and not have to wait until the flow is finished. This would allow Atlas to show the current status of a file before the whole flow is finished.</p>
<p>We are aware of the code at <a href="https://github.com/vakshorton/NifiAtlasBridge">https://github.com/vakshorton/NifiAtlasBridge</a> and <a href="https://github.com/vakshorton/NifiAtlasLineageReporter">https://github.com/vakshorton/NifiAtlasLineageReporter</a>, however it does not seem to do exactly what we want. The one problem with the above code is that it generates Atlas metadata as input and output from too many flow ingress and egress events. Many processors change or clone data, which means the FlowFile's id changes, which then in turn causes the metadata lineage to be broken in Atlas.</p>
<p>A typical simplified use-case would be to get a ZIP file from the file system, move it to a different directory based on filename and date, do various actions on it - unzip as CSV, split, join, update attributes, custom processors, manually edit it, save to a different directory, infer Avro schema, convert CSV to Avro, save file, convert file to orc, put in HDFS, generate Apache Hive DDL, create Hive table. The file names and directory names will not be hard-coded in the flow but will instead be parameter driven. In this scenario, we would like to be able to trace that Hive table lineage all the way back to the ZIP file input.</p><h2>Acceptance Criteria</h2><p>To be paid the fixed price for this opportunity, you need to&nbsp;meet all of the following criteria:</p>
<ul>
<li>A merge request from your GitHub account to this repo (<a href="https://github.com/bcgov/nifi-atlas">https://github.com/bcgov/nifi-atlas</a>) that works with the following software versions:
<ul>
<li>Java 8</li>
<li>Apache Atlas 0.8&nbsp;</li>
<li>Apache NiFi 1.3+</li>
</ul>
</li>
<li>The solution must work in a clustered environment with provenance data coming from several nodes. We would like it to work in a site-to-site environment (cluster A does some processing, then hands it over to cluster B to do further processing - we would like to be able to have the lineage follow all the way through).</li>
<li>It is acceptable for the code to work with a local file system, even though we will implement it in the cloud using e.g. Azure, AWS etc.</li>
<li>The code must allow us to add more processors and custom processors quite easily.</li>
<li>The code needs to include a build script (Maven or Gradle) to compile the Java code and produce a NAR file.</li>
<li>The code needs to include some basic unit testing, as well as an example of use in a Dataflow template to demonstrate end-to-end functionality.</li>
<li>This code does not need to be production ready, but must be a good starting point for us to use.</li>
<li>The code needs to be commented where possible, especially in the areas of provenance processing.</li>
</ul><h2>Proposal Evaluation Criteria</h2><p>We will score proposals by the following criteria:</p>
<ul>
<li>Expressed knowledge of NiFi provenance system that will employ best practices for processing provenance data efficiently as expressed in pseudocode / structures (<strong>30 </strong>points),</li>
<li>Experience contributing Java code to any public code repositories with more than 5 contributors: (<strong>10</strong> points),</li>
<li>Experience contributing Java code to either of the following projects https://github.com/apache/nifi ,https://github.com/apache/incubator-atlas (<strong>10</strong> points),</li>
<li>Ability to deliver complete solution on or before <strong>October 13, 2017</strong> (<strong>10</strong> points).</li>
</ul>

**Comment by mark-a-wilson** [comment]
Apologies -- this issue was created inadvertently -- please ignore!

**Comment by ccoldwell** [comment]
This opportunity has been assigned
